name: Test Package on macOS

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Add the Python versions you want to test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
